// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
    import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart';


// ...

// await Firebase.initializeApp(
//     options: DefaultFirebaseOptions.currentPlatform,
// );

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
// / import 'firebase_options.dart';
// / // ...
// / await Firebase.initializeApp(
//   options: DefaultFirebaseOptions.currentPlatform,
// / );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3DvmKlasa0DI0GwuGR1iXtxVwwEGhmcw',
    appId: '1:800738389190:web:831ce280958bee71233bc7',
    messagingSenderId: '800738389190',
    projectId: 'rentease-21e46',
    authDomain: 'rentease-21e46.firebaseapp.com',
    storageBucket: 'rentease-21e46.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8EGTekdiOO6pCiwMD-4QxzvdVaSpLg9M',
    appId: '1:800738389190:android:8477e4b51e1e95d4233bc7',
    messagingSenderId: '800738389190',
    projectId: 'rentease-21e46',
    storageBucket: 'rentease-21e46.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChNoYNz5m9LqLjSj_UwN61pDI0cs2w9Ys',
    appId: '1:800738389190:ios:3533aa7364e78c11233bc7',
    messagingSenderId: '800738389190',
    projectId: 'rentease-21e46',
    storageBucket: 'rentease-21e46.appspot.com',
    androidClientId: '800738389190-hbup2q6osb8f1v5md5n26d34ulorg8rd.apps.googleusercontent.com',
    iosClientId: '800738389190-euaictsc9f6fm47h1fe2p468ttapekj1.apps.googleusercontent.com',
    iosBundleId: 'com.example.minor',
  );
}
